session_name: Relationality
start_directory: './'
shell_command_before:
  - 'export PROJECT_DIR=$(pwd)'
  - 'export SSH_AUTH_SOCK=~/.ssh/auth_sock'
  - 'clear'
windows:
  - window_name: Interaction
  - window_name: Dev
